import React from 'react';
import { View, Text } from '@react-pdf/renderer';
import {
  reportStyles,
  REPORT_COLORS,
  formatReportDate,
  formatReportDateTime,
  displayOrEmpty,
} from './ReportStyles';
import type { ReportHeaderProps, ReportFooterProps } from './types';

/**
 * TUPSAFE Report Reusable Components
 * Professional components for report PDF generation
 */

/* ========== REPORT HEADER ========== */

/**
 * ReportHeader - Title, logo placeholder, dates, and filters
 * Displays at the top of every page
 */
export const ReportHeader: React.FC<ReportHeaderProps> = ({ metadata }) => {
  return (
    <View style={reportStyles.reportHeader}>
      {/* Title row with logo */}
      <View style={reportStyles.reportTitleContainer}>
        {/* Left logo placeholder */}
        <View style={reportStyles.logoPlaceholder}>
          <Text style={reportStyles.logoText}>TUP</Text>
          <Text style={reportStyles.logoText}>Logo</Text>
        </View>

        {/* Center title */}
        <View style={reportStyles.flex1}>
          <Text style={reportStyles.reportTitleText}>
            {metadata.reportTitle}
          </Text>
        </View>

        {/* Right logo placeholder (balance) */}
        <View style={reportStyles.logoPlaceholder}>
          <Text style={reportStyles.logoText}>TUPSAFE</Text>
        </View>
      </View>

      {/* Subtitle */}
      <Text style={reportStyles.reportSubtitle}>
        Technological University of the Philippines - Manila
      </Text>

      {/* Metadata row */}
      <View style={reportStyles.metadataContainer}>
        {/* Left side - Date range */}
        <View style={reportStyles.metadataItem}>
          <Text style={reportStyles.metadataLabel}>Period:</Text>
          <Text>
            {formatReportDate(metadata.startDate)} -{' '}
            {formatReportDate(metadata.endDate)}
          </Text>
        </View>

        {/* Center - Department/College filter (if applicable) */}
        {(metadata.departmentName || metadata.collegeName) && (
          <View style={reportStyles.metadataItem}>
            {metadata.departmentName && (
              <>
                <Text style={reportStyles.metadataLabel}>Department:</Text>
                <Text>{metadata.departmentName}</Text>
              </>
            )}
            {metadata.collegeName && !metadata.departmentName && (
              <>
                <Text style={reportStyles.metadataLabel}>College:</Text>
                <Text>{metadata.collegeName}</Text>
              </>
            )}
          </View>
        )}

        {/* Right side - Generated timestamp */}
        <View style={reportStyles.metadataItem}>
          <Text style={reportStyles.metadataLabel}>Generated:</Text>
          <Text>{formatReportDateTime(metadata.generatedAt)}</Text>
        </View>
      </View>

      {/* Generated by (if provided) */}
      {metadata.generatedBy && (
        <View
          style={{
            marginTop: 4,
            flexDirection: 'row',
            justifyContent: 'flex-end',
          }}
        >
          <Text style={reportStyles.metadataLabel}>Generated by:</Text>
          <Text
            style={{
              fontSize: 8,
              color: REPORT_COLORS.textGray,
              marginLeft: 4,
            }}
          >
            {metadata.generatedBy}
          </Text>
        </View>
      )}
    </View>
  );
};

/* ========== REPORT TABLE ========== */

/**
 * TableHeader - Column headers with TUP Maroon background
 */
interface TableHeaderProps {
  headers: string[];
  columnWidths?: string[];
}

export const TableHeader: React.FC<TableHeaderProps> = ({
  headers,
  columnWidths,
}) => {
  // Calculate equal widths if not provided
  const widths =
    columnWidths || headers.map(() => `${100 / headers.length}%`);

  return (
    <View style={reportStyles.tableHeader}>
      {headers.map((header, index) => (
        <View
          key={index}
          style={[
            index === headers.length - 1
              ? reportStyles.tableHeaderCellLast
              : reportStyles.tableHeaderCell,
            { width: widths[index] },
          ]}
        >
          <Text style={reportStyles.tableHeaderText}>{header}</Text>
        </View>
      ))}
    </View>
  );
};

/**
 * TableRow - Data row with alternating colors
 */
interface TableRowProps {
  data: Record<string, string | number>;
  headers: string[];
  columnWidths?: string[];
  isAlternate: boolean;
}

export const TableRow: React.FC<TableRowProps> = ({
  data,
  headers,
  columnWidths,
  isAlternate,
}) => {
  // Calculate equal widths if not provided
  const widths =
    columnWidths || headers.map(() => `${100 / headers.length}%`);

  // Get values in order using Object.values() to match the order of keys
  // This ensures values align with headers even when header display names
  // don't match the data object keys (e.g., "Employee ID" vs "employeeId")
  const values = Object.values(data);

  return (
    <View
      style={
        isAlternate ? reportStyles.tableRowAlternate : reportStyles.tableRow
      }
    >
      {headers.map((header, index) => {
        const cellValue = values[index];
        const isNumeric = typeof cellValue === 'number';

        return (
          <View
            key={index}
            style={[
              index === headers.length - 1
                ? reportStyles.tableCellLast
                : reportStyles.tableCell,
              { width: widths[index] },
            ]}
          >
            <Text
              style={
                isNumeric
                  ? reportStyles.tableCellTextCenter
                  : reportStyles.tableCellText
              }
            >
              {displayOrEmpty(cellValue)}
            </Text>
          </View>
        );
      })}
    </View>
  );
};

/**
 * EmptyTableRow - Displayed when no data is available
 */
export const EmptyTableRow: React.FC = () => {
  return (
    <View style={reportStyles.tableRow}>
      <View
        style={[
          reportStyles.tableCell,
          { width: '100%', alignItems: 'center' },
        ]}
      >
        <Text
          style={[
            reportStyles.tableCellText,
            { fontStyle: 'italic', color: REPORT_COLORS.textGray },
          ]}
        >
          No data available for the selected period.
        </Text>
      </View>
    </View>
  );
};

/* ========== REPORT FOOTER ========== */

/**
 * ReportFooter - Page numbers and confidential notice
 * Fixed at the bottom of every page
 */
export const ReportFooter: React.FC<ReportFooterProps> = ({
  pageNumber,
  totalPages,
}) => {
  return (
    <View style={reportStyles.pageFooter} fixed>
      {/* Left - Confidential notice */}
      <Text style={reportStyles.footerText}>
        Confidential - TUPSAFE TUP Manila
      </Text>

      {/* Right - Page numbers */}
      <Text style={reportStyles.pageNumber}>
        Page {pageNumber} of {totalPages}
      </Text>
    </View>
  );
};

/* ========== UTILITY COMPONENTS ========== */

/**
 * SectionHeader - Optional section divider for multi-section reports
 */
interface SectionHeaderProps {
  title: string;
}

export const SectionHeader: React.FC<SectionHeaderProps> = ({ title }) => {
  return (
    <View
      style={{
        marginTop: 15,
        marginBottom: 8,
        paddingBottom: 4,
        borderBottomWidth: 1,
        borderBottomColor: REPORT_COLORS.tupMaroon,
      }}
    >
      <Text
        style={{
          fontSize: 12,
          fontWeight: 'bold',
          color: REPORT_COLORS.tupMaroon,
        }}
      >
        {title}
      </Text>
    </View>
  );
};
